# Nixpacks configuration for Coolify deployment

[phases.build]
# Custom build commands after dependencies are installed
cmds = [
    "pnpm run build:client",
    "pnpm run build:server"
]

[start]
# Run the production server
cmd = "node dist/server.js"